// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using PortfolioValue.EODHistorical;
//
//    var fundamentalStock = FundamentalStock.FromJson(jsonString);

namespace PortfolioValue.EODHistorical
{
    using PortfolioValue.EODHistorical.BusinessObjects;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    using System.Globalization;

    public partial class BulkFundamentalStocks : Dictionary<int, FundamentalStock>
    {
    }
    
    public partial class BulkFundamentalStocks
    {
        public static BulkFundamentalStocks FromJson(string json)
        {
            json = json.Replace("\"0000-00-00\"", "null");
            return JsonConvert.DeserializeObject<BulkFundamentalStocks>(json, PortfolioValue.EODHistorical.ConverterFundamentalStock.Settings);
        }
    }
}
